defmodule DCATR.Directory do
  @moduledoc """
  A named collection of graphs and nested directories.

  Directories enable hierarchical organization of graphs, providing structure for navigation,
  scoped metadata, and targeted operations.

  Each directory can contain `DCATR.Graph`s and nested `DCATR.Directory`s as members.

  ## Access Functions

  ### Direct access (non-recursive)

  - `members/1` - all direct Element members
  - `graphs/1` - direct Graph members only (callback)
  - `directories/1` - direct Directory members only (callback)

  ### Recursive access (generated by `DCATR.Directory.Type`)

  - `all_graphs/1` - all Graphs through entire sub-directory tree
  - `all_members/1` - all Elements through entire sub-directory tree
  - `find_graph/2` - find Graph by ID recursively
  """

  use DCATR.Directory.Type

  alias DCATR.Directory.LoadHelper

  import DCATR.Utils, only: [bang!: 2]

  schema DCATR.Directory < DCATR.Element do
    link members: DCATR.member(), type: list_of(DCATR.Element), depth: +1
  end

  def new(id, attrs \\ []) do
    with {:ok, struct} <- build(id, attrs) do
      Grax.validate(struct)
    end
  end

  def new!(id, attrs \\ []), do: bang!(&new/2, [id, attrs])

  # Override generated members/1 for direct field access to avoid double-filtering
  def members(%__MODULE__{members: members}), do: members

  @impl true
  def on_load(%__MODULE__{} = directory, %RDF.Graph{} = graph, _opts) do
    LoadHelper.normalize_from_sub_properties(directory, graph)
  end

  def on_load(_directory, _description, _opts),
    do: raise(ArgumentError, "on_load requires an RDF.Graph, not an RDF.Description")
end
